# manual event
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'default value'
      int_input:
        description: 'sometimes the number of the beast'
        required: true
        default: 666
        type: number
      choicee_input:
        description: 'A choice input'
        required: false
        default: 'hest'
        type: choice
        options:
          - hest
          - ged
          - fisk 

  push:
    branches:
      - main
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hi"

  acknowledge_hi:
    runs-on: ubuntu-latest
    needs: say_hi
    steps:
      - name: acknowledge hi
        run: echo "hi acknowledged"

  continue_conversation:
    runs-on: ubuntu-latest
    needs: acknowledge_hi
    steps:
      - name: continue conversation
        run: |
          echo 'conversation continued ${{ github.event.inputs.int_input }} test'
