# manual event
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'default value'
  push:
    branches:
      - main
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hi"
